name: Test cs-resolve

on:
  push:
    branches:
      - main
    paths:
      - cs-resolve/**
      - .github/workflows/test-cs-resolve.yml
  pull_request:
    paths:
      - cs-resolve/**
      - .github/workflows/test-cs-resolve.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
            6.0.x
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('cs-resolve/**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: setup CompetitiveVerifierCsResolver
        run: dotnet tool install -g CompetitiveVerifierCsResolver
      - name: C# build
        run: dotnet build cs-resolve/tests/tests.sln -c Release
      - name: C# test
        run: dotnet test cs-resolve/tests/tests.sln --logger  "CompetitiveVerifier;OutDirectory=${{runner.temp}}/VerifierUnitTestCs" --no-build  -c Release
      - name: C# verifications
        run: dotnet run --project cs-resolve/tests/VerifyApp/VerifyApp.csproj --no-build -c Release | tee ${{runner.temp}}/problems.json

      - name: cs-resolve
        id: resolve
        uses: ./cs-resolve
        with:
          solution: cs-resolve/tests/tests.sln
          include: cs-resolve/tests
          exclude: "**/Usings.cs **/obj/** **/bin/**"
          output-path: ./verify-files.json
          msbuild-properties: Configuration=Release
          unittest-result: ${{runner.temp}}/VerifierUnitTestCs/*.csv
          problems: ${{runner.temp}}/problems.json

      - name: Check path
        run: |
          test "${{steps.resolve.outputs.json-path}}" = "./verify-files.json"

      - name: Replace expected path
        id: expected
        run: |
          sed -e "s:{{{PWD}}}:$PWD:g" cs-resolve/tests/expected.json > $RUNNER_TEMP/actual-expected.json
          echo "json-path=$RUNNER_TEMP/actual-expected.json" >> $GITHUB_OUTPUT

      - name: Set up competitive-verifier
        uses: ./setup
        with:
          python-version: "3.9"

      - name: equal
        uses: ./testing/verifier-object-equality-action
        with:
          class: VerificationInput
          file1: ${{steps.resolve.outputs.json-path}}
          file2: ${{steps.expected.outputs.json-path}}
